#Requires -Version 7.2
<#
.SYNOPSIS
Generate a draft using an actual tenant-exported Settings Catalog scaffold.
.DESCRIPTION
Never invents Graph IDs or choice options. Bindings explicitly connect assessed
source keys to reviewed target definitions. This script only writes local files.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Assessment,
    [Parameter(Mandatory)][string]$SourcePolicyId,
    [Parameter(Mandatory)][string]$Template,
    [Parameter(Mandatory)][string]$Bindings,
    [string]$OutputPath='./Draft',
    [switch]$AllowPartial
)
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'src/AppleDDM.psm1') -Force
$a=Get-Content -LiteralPath $Assessment -Raw | ConvertFrom-Json -AsHashtable
$t=Get-Content -LiteralPath $Template -Raw | ConvertFrom-Json -AsHashtable
$b=Get-Content -LiteralPath $Bindings -Raw | ConvertFrom-Json -AsHashtable
if($a.schemaVersion -ne 1 -or $b.schemaVersion -ne 1){throw 'Unsupported assessment or binding schema.'}
if($t.platforms -notin @('iOS','macOS') -or $t.technologies -ne 'mdm'){throw 'Expected an iOS/macOS Settings Catalog template with mdm technology.'}
$rows=@($a.settings | Where-Object {$_.sourcePolicyId -ceq $SourcePolicyId})
if(-not $rows.Count){throw 'Source policy ID not found.'}
$sourcePlatform=if($rows[0].Contains('platform')){$rows[0].platform}else{'iOS'}
if($sourcePlatform -ne $t.platforms){throw 'Source and target scaffold platform differ.'}
$leaves=@($t.settings | ForEach-Object {Get-DDMInstanceLeaves $_.settingInstance})
if(-not $leaves.Count){throw 'Template has no settings.'}
$boundKeys=[Collections.Generic.List[string]]::new(); $targetIds=@{}
foreach($binding in $b.bindings) {
    if($targetIds.ContainsKey($binding.targetDefinitionId)){throw 'Duplicate target binding.'}
    $targetIds[$binding.targetDefinitionId]=$true
    $source=@($rows | Where-Object {$_.sourceKey -ceq $binding.sourceKey})
    if($source.Count -ne 1 -or $source[0].classification -notin @('DDM_DIRECT','DDM_SEMANTIC')){throw "Source is ambiguous or not a verified candidate: $($binding.sourceKey)"}
    if($binding.targetPath -cne $source[0].targetPath){throw 'Binding target path does not match the assessed mapping.'}
    $target=@($leaves | Where-Object {$_.key -ceq $binding.targetDefinitionId})
    if($target.Count -ne 1){throw 'Target ID must occur exactly once; repeated groups/collections require manual handling.'}
    $instance=$target[0].instance; $value=$source[0].proposedValue
    if($instance.ContainsKey('simpleSettingValue')) {
        $type=$instance.simpleSettingValue['@odata.type']
        if($type -match 'IntegerSettingValue$' -and ($value -is [int] -or $value -is [long])) { $instance.simpleSettingValue.value=$value }
        elseif($type -match 'StringSettingValue$' -and $value -is [string]){$instance.simpleSettingValue.value=$value}
        else{throw 'Template simple value type does not match proposed value.'}
    } elseif($instance.ContainsKey('choiceSettingValue')) {
        if(-not $binding.ContainsKey('optionMap')){throw 'Choice target requires an explicit optionMap copied from real definition options.'}
        $key=if($value -is [bool]){$value.ToString().ToLowerInvariant()}else{[string]$value}
        if(-not $binding.optionMap.ContainsKey($key)){throw "No reviewed option for $key"}
        $instance.choiceSettingValue.value=$binding.optionMap[$key]
    } else{throw 'Only single simple/choice values can be generated in v0.1.'}
    $boundKeys.Add($binding.sourceKey)
}
$structural=@();if($b.ContainsKey('structuralDefinitionIds')){$structural=@($b.structuralDefinitionIds)}
foreach($leaf in $leaves) {
    if(-not $targetIds.ContainsKey($leaf.key)) {
        # Explicitly approved choice parent used to enable its mapped children.
        if($leaf.key -notin $structural -or -not $leaf.instance.ContainsKey('choiceSettingValue') -or @($leaf.instance.choiceSettingValue.children).Count -eq 0){throw "Unbound template value: $($leaf.key). Remove unrelated settings or bind it."}
    }
}
$omitted=@($rows | Where-Object {$_.sourceKey -cnotin $boundKeys.ToArray()})
if($omitted.Count -gt 0 -and -not $AllowPartial){throw "$($omitted.Count) source settings are not represented. Use -AllowPartial for a clearly marked draft, retaining the source."}
function Clean-Instances($node) {
    if($node -is [Collections.IDictionary]) {
        foreach($key in @($node.Keys)) {
            if($key -in @('id','settingInstanceTemplateReference','settingValueTemplateReference') -or ($key.StartsWith('@odata.') -and $key -ne '@odata.type')){$node.Remove($key)}
            else{Clean-Instances $node[$key]}
        }
    } elseif($node -is [array]){foreach($item in $node){Clean-Instances $item}}
}
$settings=@($t.settings | ForEach-Object {@{'@odata.type'='#microsoft.graph.deviceManagementConfigurationSetting';settingInstance=$_.settingInstance}})
Clean-Instances $settings
$policy=@{name="MIGRATION - $($rows[0].sourcePolicyName) - DDM";description="Generated by AppleDDMMigrator v0.2.4. Source ID: $SourcePolicyId. Mapped $($boundKeys.Count)/$($rows.Count). Review all prerequisites and retain the source. Generated $([datetime]::UtcNow.ToString('o')).";platforms=$sourcePlatform;technologies='mdm';settings=$settings}
$manifest=@{schemaVersion=1;platform=$sourcePlatform;sourcePolicyId=$SourcePolicyId;sourceTenantId=$a.tenantId;generatedAt=[datetime]::UtcNow.ToString('o');mapped=$boundKeys.Count;sourceSettings=$rows.Count;omittedSettings=$omitted;sourceReplacementApproved=$false;assignments=@();bindings=$b;templateSha256=(Get-FileHash -LiteralPath $Template -Algorithm SHA256).Hash;policySha256=''}
$null=New-Item -Path $OutputPath -ItemType Directory -Force
$policyPath=Join-Path $OutputPath 'proposed-policy.json'
Write-DDMJson $policy $policyPath
$manifest.policySha256=(Get-FileHash -LiteralPath $policyPath -Algorithm SHA256).Hash
Write-DDMJson $manifest (Join-Path $OutputPath 'migration-manifest.json')
Write-Host "Draft generated: $policyPath. Assignments: NONE. Omitted settings: $($omitted.Count). Source replacement is NOT approved."
